# Generated by Django 3.2 on 2021-05-30 01:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Boleta',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_emision', models.DateField()),
                ('estado', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'boleta',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FamiliaProducto',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'familia_producto',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FichaEconomica',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_ficha', models.CharField(max_length=50)),
                ('documento', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'ficha_economica',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Hora',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('estado', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'hora',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='OrdenPedido',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_solicitada', models.DateField()),
            ],
            options={
                'db_table': 'orden_pedido',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='OrdenPedidoProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio_unitario', models.BigIntegerField()),
                ('cantidad', models.BigIntegerField()),
            ],
            options={
                'db_table': 'orden_pedido_producto',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('rut', models.CharField(max_length=20, unique=True)),
                ('contraseña', models.CharField(max_length=20)),
                ('nombre', models.CharField(max_length=50)),
                ('apellido_paterno', models.CharField(max_length=50)),
                ('apellido_materno', models.CharField(max_length=50)),
                ('fecha_nacimiento', models.DateField()),
                ('telefono', models.CharField(max_length=20)),
                ('correo_electronico', models.CharField(max_length=80)),
                ('estado', models.CharField(max_length=1)),
            ],
            options={
                'db_table': 'persona',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30)),
                ('precio_venta', models.BigIntegerField()),
                ('stock', models.BigIntegerField()),
                ('stock_minimo', models.BigIntegerField()),
                ('estado', models.CharField(max_length=1)),
            ],
            options={
                'db_table': 'producto',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('rubro', models.CharField(max_length=200)),
                ('nombre_contacto', models.CharField(max_length=50)),
                ('apellido_contacto', models.CharField(max_length=50)),
                ('telefono_contacto', models.CharField(max_length=30)),
                ('correo_contacto', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'proveedor',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Recepcion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
            ],
            options={
                'db_table': 'recepcion',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RecepcionProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.BigIntegerField()),
                ('fecha_vencimiento', models.DateField()),
            ],
            options={
                'db_table': 'recepcion_producto',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=150)),
            ],
            options={
                'db_table': 'servicio',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ServicioProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.BigIntegerField()),
            ],
            options={
                'db_table': 'servicio_producto',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TipoUsuario',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'tipo_usuario',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='HoraServicio',
            fields=[
                ('hora', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='core.hora')),
            ],
            options={
                'db_table': 'hora_servicio',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PersonaTipoUsuario',
            fields=[
                ('persona', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='core.persona')),
            ],
            options={
                'db_table': 'persona_tipo_usuario',
                'managed': False,
            },
        ),
    ]
